### ISSUE TITLE
Invalid or corrupt jarfile serverstarter-1.2.7.jar Mac OSx 10.15.4

### ISSUE THREAD

**Issue by Seba13xp** [BloodyMods/ServerStarter#19]
can't start All The Mods 5 modpack with its jar on Mac.
### Log
`https://github.com/BloodyMods/ServerStarter/releases/download/v1.2.7/serverstarter-1.2.7.jar
DEBUG: (curl) Downloading https://github.com/BloodyMods/ServerStarter/releases/download/v1.2.7/serverstarter-1.2.7.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   636  100   636    0     0   2200      0 --:--:-- --:--:-- --:--:--  2208
Error: Invalid or corrupt jarfile serverstarter-1.2.7.jar`

**Comment by Cntrldfusion** [comment]
I was having the same problem in 10.15.6 with ATM 6.  Not sure if it's how the script downloads serverstart-1.2.7.jar from this repository or not but I downloaded the zip file fdirectly from this GitHub repository and then used the serverstart-1.2.7.jar file from it.

**Comment by DustRaven** [comment]
This is very likely due to the fact, that the curl call in the serverstart.sh file is incorrect. It does not follow redirects, thus downloads the wrong file.
