### ISSUE TITLE
BitDefender Flags ATM6 Server Start .bat as Threat

### ISSUE THREAD

**Issue by darkzirconia** [BloodyMods/ServerStarter#23]
Specifically BitDefender Total Security flags the startserver.bat file for All the Mods 6 with the threat "Heur.BZC.ONG.Leopard.1.41E93A41"

I've raised this issue with the modpack creator and they directed me to raise it with you:
https://github.com/AllTheMods/ATM-6/issues/71#issuecomment-674913682

**Comment by BloodWorkXGaming** [comment]
There is honestly not much I can do about that. BitDefender is playing it safe here, as that script downloads a file from the internet and executes it. It doesn't know that file is a trusted file from Forge/Minecraft.
