### ISSUE TITLE
server.properties

### ISSUE THREAD

**Issue by Karrq** [BloodyMods/ServerStarter#24]
Hello I'm a user of this tool (ATM6 uses this for their server currently) and I was about to enter my `server.properties` to enable rcon but it seems to be missing?

Can you help me?
The format specification example also seems to be missing any option regarding this..

**Comment by BloodWorkXGaming** [comment]
I'm sorry, but RCON has nothing to do with the ServerStarter as that is provided by MC itself. If it doesn't get generated that is a bug/misconfiguration on the MC/Forge Side.

If you still have this problem you could attempt to put them there by hand
