### ISSUE TITLE
Not using Enough Ram and CPU

### ISSUE THREAD

**Issue by Sotabi** [BloodyMods/ServerStarter#27]
First of all, sorry for my bad English.
I'am running the ATM3R Modpack on an VM Sphere Host with 60GB RAM and 8VCPUs. But it only uses 20 GB and 7 GHZ.

The Server is very slow, but i dont know, what the problem is. When i use the "normal way" it uses 60GB and 15-20GHZ, so i think the problem is with the Server Starter, but after Hours, i cant find a solution.

So i hope you can help me.

Some More Infos:

Modpack has around 300 Mods

Server Hardware:
2x (12 CPUs x Intel(R) Xeon(R) CPU X5660 @ 2.80GHz)
192 GB RAM

The "server-setup-config.yaml"
[server-setup-config.txt](https://github.com/BloodyMods/ServerStarter/files/5328746/server-setup-config.txt)

My Host:
![VM Host](https://user-images.githubusercontent.com/51969825/95106885-6d1bc980-0739-11eb-98f2-8493558abb73.PNG)

Thanks,
Sotabi

**Comment by BloodWorkXGaming** [comment]
Well, there not really a difference between starting it from another java instance vs starting from the commandline.
The only difference is the parameters you are passing.
Which ones are you using when you start it without this programm?

**Comment by BloodWorkXGaming** [comment]
Also from experience i can tell you, that minecraft works better with high-speed low-corecount processors than with lower-herz  manycores as it is generally not that multithreaded
therefore i doubt that is even using half of the 24 cores available

and a high ram amount may cause lag spikes as well, as java tends to slack with the garbage collection and do a lot in one go (atleast it did on earlier versions)

**Comment by Sotabi** [comment]
> Well, there is not really a difference between starting it from another java instance vs starting from the commandline.
> The only difference are the parameters you are passing.
> Which ones are you using when you start it without this programm?

This is what i have in my start.sh:
screen -AmdS modpack java -jar -Xms8G -Xmx32G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch forge.jar nogui

**Comment by Sotabi** [comment]
> Also from experience i can tell you, that minecraft works better with high-speed low-corecount processors than with lower-herz manycores as it is generally not that multithreaded
> therefore i doubt that is even using half of the 24 cores available
> 
> and a high ram amount may cause lag spikes as well, as java tends to slack with the garbage collection and do a lot in one go (atleast it did on earlier versions)

Okay,I knew that, but I though, VM Sphere supplies the VM Hosts with Processing Power not Cores (Explains the 20GHz).
So there isn't a think i can do?

**Comment by BloodWorkXGaming** [comment]
Yeah, you are using way different parameters in your own starter file than the serverstarter is using, you can change those at the bottom of the config file.

Not sure how vm sphere works, but i can't imagine how it would emulate multiple cores as one single core. As cores have private and shared processor parts that would be near impossible to do (afaik atleast)

**Comment by Sotabi** [comment]
Okay, thanks, for the quick help.
As a suggestion: A little explanation / tutorial would be nice, so you know what exactly the ServerStarter does and where you have to edit things.
