### ISSUE TITLE
Add config to skip ping test or ignore ping failure

### ISSUE THREAD

**Issue by xinyuan-liu** [BloodyMods/ServerStarter#33]
My network provider filtered out ICMP packets so I can't ping. I'm now stuck here but I DO have network access.

**Comment by BloodWorkXGaming** [comment]
There is already a config Option to disable the network check, can Look for the exact name tomorrow :)
________________________________
From: xinyuan liu ***@***.***>
Sent: Wednesday, April 28, 2021 3:05:11 PM
To: BloodyMods/ServerStarter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BloodyMods/ServerStarter] Add config to skip ping test or ignore ping failure (#33)


My network provider filtered ICMP packets so I can't ping. I'm now stuck he but I DO have network access.

**Comment by BloodWorkXGaming** [comment]
Set this to false to disable
https://github.com/BloodyMods/ServerStarter/blob/master/server-setup-config.yaml#L158
