### ISSUE TITLE
Make Internet connection checker flexible

### ISSUE THREAD

**Issue by Taskeren** [BloodyMods/ServerStarter#52]
PCs in mainland of China can never access Google, but may connect with CurseForge. Maybe there can be a config section to disable the connection check.

Also, when the connection is bad, some mod cannot be downloaded properly while most of others are fine. Maybe there can be a list of mods that are not downloaded, for users to download it manually.

**Comment by BloodWorkXGaming** [comment]
Added a configurable list of servers, and it also won't exit but rather only warn the user now in 2.3.0 :)
