### ISSUE TITLE
Server won't start by default if example.com does not respond.

### ISSUE THREAD

**Issue by LauJosefsen** [BloodyMods/ServerStarter#55]
When the server starts, it will ping google.com and example.com and will refuse to start by default if **any** of these sites is unavailable. I had to add an entry to my hosts file in order to boot the server.

I would argue that example.com is not an ideal domain to use for this purpose. I propose using a web resource with a high uptime, such as https://1.1.1.1 or don't even check for internet connection at start up.

Checking for internet connection is arguably not needed, as curseforge and other sites could be down, even though your connection is working fine. The unavailability of resources could be handled where appropriately.

**Comment by LucasLundJensen** [comment]
http://example.com is also blocked by some DNS (for some odd reason), I had that exact problem and had to switch over to 8.8.8.8, 8.8.4.4

**Comment by BloodWorkXGaming** [comment]
Added a configurable list of servers, and it also won't exit but rather only warn the user now in 2.3.0 :)
