### ISSUE TITLE
Remove InternetManager.checkConnection() ?

### ISSUE THREAD

**Issue by CubeSugarCheese** [BloodyMods/ServerStarter#58]
# Why?
I think this check is Unnecessary. If you can connect to google.com, it doesn't mean you can connect other domain. vice versa.
# Suggestion
remove the internet checking. All http request should use `try` and catch request Exceptions. while exception occurs, program should catch and report it (with detailed stack trace).

>

**Comment by LauJosefsen** [comment]
I agree, there is no real reason to check for connection to arbitrary domains at startup.

A connection to google or curseforge at startup, does definitely not assure the program that the next http request to curseforge will not fail.

See also #52  #53 #55

**Comment by BloodWorkXGaming** [comment]
Added a configurable list of servers, and it also won't exit but rather only warn the user now in 2.3.0 :)
