### ISSUE TITLE
Uses wrong Java when multiple are installed

### ISSUE THREAD

**Issue by YoYoK3nny** [BloodyMods/ServerStarter#62]
### System Details
OS: Windows 10
Arch: 64-bit
Java: 8 & 17

### Modpack
Name: ATM7
Version: 0.3.12

### ServerStarter
Version tried: 2.2.0 & 2.3.1

### Problem
When there are multiple versions of Java installed, the wrong java is used to launch the server.

### Solution
Add to the spec which Java version is required for the server to run. If the current Java isn't that version, check to see if the required version is available to use and use it if it is.

### Temporary Workaround
Have currently set the forcedJavaPath to where Java 17 is installed.

**Comment by BloodWorkXGaming** [comment]
This was actually just added in version 2.3.
You can set `  supportedJavaVersions: [17]`, then it looks for the correct java version

https://github.com/BloodyMods/ServerStarter/blob/master/server-setup-config.yaml#L201

**Comment by YoYoK3nny** [comment]
That worked, though I had to completely change my Java setup, since the feature doesn't seem to check the `HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment` registry keys for runtimes added via the Java Control Panel.

**Comment by BloodWorkXGaming** [comment]
No, it only checks for the Environment Variable `PATH`
The registry key is no universal indicator for installed java versions, for example, I have at least 3 Versions installed but no Version is listed in the registry key.
