### ISSUE TITLE
Server not starting, cant find java

### ISSUE THREAD

**Issue by apstarz** [BloodyMods/ServerStarter#64]
![unknown](https://user-images.githubusercontent.com/16158951/165183186-9adc4756-a0b8-4235-8f50-78bcd85a8895.png)
This is not working and this is the error

**Comment by YoYoK3nny** [comment]
You need to use the serverstarter.bat from the release .zip, not the .jar (or edit to match the jar file)

**Comment by apstarz** [comment]
> 

I have been opening it from the .bat and thats the error i get

**Comment by BloodWorkXGaming** [comment]
Where did you get the bat file from? 
A compiled release or the `resource` folder?

Only the compiled releases have the correct version string inside of them

**Comment by apstarz** [comment]
> Where did you get the bat file from? A compiled release or the `resource` folder?
> 
> Only the compiled releases have the correct version string inside of them

I got it from the folder on curses forge then I downloaded the newest serverstarter ZIP from there github

**Comment by apstarz** [comment]
> Apparently you have a wrong .bat file obtained from somewhere. What folder from curse did you get it? And did you download the `[serverstarter-2.3.1.zip](https://github.com/BloodyMods/ServerStarter/releases/download/v2.3.1/serverstarter-2.3.1.zip)` folder from github? The sources zip would be wrong.

I did download that version and also tried the 2.0 version with the pack from the cursed force, none of them work?

**Comment by apstarz** [comment]
> Apparently you have a wrong .bat file obtained from somewhere. What folder from curse did you get it? And did you download the `[serverstarter-2.3.1.zip](https://github.com/BloodyMods/ServerStarter/releases/download/v2.3.1/serverstarter-2.3.1.zip)` folder from github? The sources zip would be wrong.

My friend has fixed it for me and now works, ty
